# Base configs
baseurl: "https://codingnirvana.in/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by Rajesh Muppalla"
subtitle: "See the world through my eyes!"
author: "Rajesh Muppalla"
header:
 title: "Photography"
 subtitle: "by Rajesh Muppalla"
footer:
 name: "Hey there, my name is Rajesh"
 bio: "I am a software engineer from India trying my hands at Bird Photography."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/codingnirvana/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/codingnirvana"
  twitter: "https://www.twitter.com/codingnirvana"
  instagram: "https://www.instagram.com/codingnirvana"
  dribbble: ""
  linkedin: "https://in.linkedin.com/in/codingnirvana"
  github: "https://www.github.com/codingnirvana"
